#AUTHOR: "AtomicGamer9523"@github.com
#LICENSE: "Creative Commons CC0 1.0"
#FORMAT: "TOML"
[package]
name = "hyperhasher"
version = "0.1.0"
edition = "2018"
license = "Creative Commons CC0 1.0"

[dependencies]
chrono = "0.4"
blake2 = "0.10.4"